week2/day2/FLASK_EXAMPLE/app.py
from flask import Flask
from views import views
# we import our viewws from the views file

app = Flask(__name__)
# we instantiate the app object

app.register_blueprint(views)
# we register the views Blueprint

if __name__ == "__main__":
    app.run(debug=True, port=8000)

# running the application

week2/day2/FLASK_EXAMPLE/views.py
from flask import render_template, Blueprint, request

views = Blueprint('views', __name__)

# view in this instance is a Blueprint

task_list = [

]

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/contact')
def contact():
    return render_template('contact.html')

@views.route('/about')
def about():
    return render_template('about.html')

@views.route('/todos', methods=["GET", "POST"])
def todos():
    if request.method == "POST":
        task = request.form.get("task-input")
        task_list.append(task)
        print(task_list)
        return render_template('todos.html', task_list=task_list)
    return render_template('todos.html')

week2/day2/FLASK_EXAMPLE/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About</h1>
{% endblock %}

week2/day2/FLASK_EXAMPLE/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
    <title></title>
</head>
<body id="base-body">
    <nav>
        <a href="{{ url_for('views.home') }}">Home</a>
        <a href="{{ url_for('views.contact') }}">Contact</a>
        <a href="{{ url_for('views.about') }}">About</a>
        <a href="{{ url_for('views.todos') }}">ToDos</a>
        <button onclick="darkMode()">Dark Mode</button>
    </nav>
    {% block content %}
    {% endblock %}
<span id="date" onload="displayDate()"></span>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
<script>document.getElementById("date").innerHTML = Date();</script>
</body>
</html>

week2/day2/FLASK_EXAMPLE/templates/contact.html
{% extends 'base.html' %}

{% block content %}
<h1>Contacts</h1>
{% endblock %}

week2/day2/FLASK_EXAMPLE/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Bretts website</h1>
{% endblock %}

week2/day2/FLASK_EXAMPLE/templates/todos.html
{% extends 'base.html' %}

{% block content %}
<h1>ToDo Manager</h1>
<br>
<div>
    <div id="task-box">
    <h2>New Tasks:</h2>

    <ul>
        {% for task in task_list %}

        {% if "now" in task %}
        <strong>!Important</strong>
        {% endif %}

        <li>{{ task }}</li>
        {% endfor %}

    </ul>

    </div>
    <button onclick="taskHider()">Show/Hide Tasks</button>
    <form action="/todos" method="POST">
        <input type="text" name="task-input" id="task-input">
        <input type="submit" value="Add Task">
    </form>

</div>
{% endblock %}